module.exports = {
  AccessPattern: {
    MovieTheater: 'MovieTheater',
    User: 'User',
    EventBooking: 'EventBooking',
    TicketBooking: 'TicketBooking',
  },
  ServerEnum: {
    RESPONSE_CONNECTION_ERROR: "CONNECTION ERROR",
    RESPONSE_SUCCESS: "SUCCESS",
    RESPONSE_DATABASE_CONNECTION_ERROR: "DATABASE CONNECTION ERROR",
    RESPONSE_PASSWORD_MISMATCH: "PASSWORD MISMATCH",
    RESPONSE_EMAIL_MISMATCH: "EMAIL MISMATCH",
    RESPONSE_OTP_MISMATCH: "OTP MISMATCH",
    RESPONSE_EMAIL_TAKEN: "EMAIL TAKEN",
    RESPONSE_PHONE_TAKEN: "PHONE TAKEN",
    RESPONSE_INVALID_JWT_TOKEN: "INVALID JWT TOKEN",
    RESPONSE_USER_ALREADY_ADDED: "USER ALREADY ADDED",
    RESPONSE_USER_NOT_FOUND: "USER NOT FOUND",
    RESPONSE_GROUP_NOT_FOUND: "TEAM NOT FOUND",
    RESPONSE_ACCOUNT_NOT_ACTIVE: "ACCOUNT IS NOT ACTIVATE",
    RESPONSE_HOLIDAY_IN_USE: "THIS PUBLIC HOLIDAY IS REFERENCED.",
    RESPONSE_ACCESS_DENIED: "ACCESS DENIED",
    RESPONSE_ALREADY_REGISTERED: 'Already Registered user with the email',
    RESPONSE_THEATER_TIME_CONFLICT: 'This theater is already booked for this time',

    STATUS_PENDING: 'IN PROGRESS',
    STATUS_COMPLETE: 'COMPLETED',
    STATUS_GET_STARTED: 'GET STARTED',

    YES: 'YES',
    NO: 'NO'

  }
};
